apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  namespace: ya0534516378-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
